-- lua/comment_filename/config.lua
local M = {}

M.defaults = {
  enabled = true,
  patterns = {
    "*.js",
    "*.jsx",
    "*.ts",
    "*.tsx",
    "*.mjs",
    "*.cjs",
    "*.lua",
    "*.py",
    "*.rb",
    "*.pl",
    "*.php",
    "*.r",
    "*.c",
    "*.h",
    "*.cpp",
    "*.hpp",
    "*.cc",
    "*.hh",
    "*.m",
    "*.mm",
    "*.cu",
    "*.rs",
    "*.go",
    "*.java",
    "*.kt",
    "*.kts",
    "*.scala",
    "*.groovy",
    "*.swift",
    "*.dart",
    "*.sh",
    "*.bash",
    "*.zsh",
    "*.fish",
    "*.html",
    "*.htm",
    "*.css",
    "*.scss",
    "*.less",
    "*.vue",
    "*.svelte",
    "*.astro",
    "*.sql",
    "*.toml",
    "*.conf",
    "*.ini",
    "*.gitconfig",
    "*.nginx",
    "Dockerfile",
    "dockerfile",
    "*.mk",
    "Makefile",
    "*.cmake",
    "CMakeLists.txt",
    "*.nix",
    "Chart.yaml",
  },
  filetypes = {
    -- web
    javascript = true,
    typescript = true,
    javascriptreact = true,
    typescriptreact = true,
    vue = true,
    svelte = true,
    astro = true,
    html = false,
    css = true,
    scss = true,
    less = true,
    -- scripts
    sh = true,
    bash = true,
    zsh = true,
    fish = true,
    -- general
    lua = true,
    vim = true,
    python = true,
    ruby = true,
    perl = true,
    php = true,
    r = true,
    -- systems
    c = true,
    cpp = true,
    objc = true,
    objcpp = true,
    cuda = true,
    rust = true,
    go = true,
    zig = true,
    v = true,
    d = true,
    nim = true,
    crystal = true,
    -- JVM & friends
    java = true,
    kotlin = true,
    scala = true,
    groovy = true,
    -- mobile/other
    swift = true,
    dart = true,
    -- functional
    haskell = true,
    elixir = true,
    erlang = true,
    ocaml = true,
    clojure = true,
    lisp = true,
    scheme = true,
    julia = true,
    fsharp = true,
    -- .NET
    csharp = true,
    -- markup/document
    tex = false,
    latex = false,
    markdown = false,
    -- data / config (only those that accept a clear comment)
    sql = true,
    toml = true,
    conf = true,
    dosini = true,
    gitconfig = true,
    nginx = true,
    dockerfile = true,
    make = true,
    cmake = true,
    nix = true,
    helm = true,
    -- note: yaml/json have poor comment support; excluded intentionally
  },
  skip_gitignored = true,
}

function M.merge(opts)
  M.opts = vim.tbl_deep_extend("force", vim.deepcopy(M.defaults), opts or {})
  return M.opts
end

function M.get()
  return M.opts or M.defaults
end

return M
